# Generated by Django 5.1.2 on 2024-10-18 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='para_llevar',
            new_name='Consumir',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='estado',
            new_name='Estado',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='nombre_pedido',
            new_name='Pedido',
        ),
    ]
