# Generated by Django 5.1.2 on 2024-10-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_para_llevar_pedido_consumir_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='Consumir',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='Pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_cliente',
            field=models.CharField(default='Cliente Anónimo', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observaciones',
            field=models.CharField(choices=[('sin salsas', 'Sin Salsas'), ('sin salsa blanca', 'Sin Salsa Blanca'), ('con mostaza', 'Con Mostaza'), ('sin salsa roja', 'Sin Salsa Roja'), ('sin mostaza', 'Sin Mostaza'), ('sin cebolla', 'Sin Cebolla'), ('sin pepinillos', 'Sin Pepinillos'), ('con todas las salsas', 'Con Todas las Salsas')], default='con todas las salsas', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='parallevar',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.CharField(choices=[('hamburguesa', 'Hamburguesa'), ('hotdog', 'Hot Dog'), ('taco', 'Taco'), ('enchiladas', 'Enchiladas'), ('sandwich qbano', 'Sandwich Qbano'), ('burritos', 'Burritos'), ('arepa rellena', 'Arepa Rellena')], default='hamburguesa', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('en espera', 'En Espera'), ('en preparacion', 'En Preparación'), ('terminado', 'Terminado')], default='en espera', max_length=50),
        ),
    ]
