# Generated by Django 5.1.2 on 2024-10-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_remove_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
    ]
