# Generated by Django 5.1.2 on 2024-10-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_rename_observaciones_pedido_observacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='observacion',
            new_name='observaciones',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('en espera', 'En Espera'), ('en preparacion', 'En Preparación'), ('terminado', 'Terminado')], default='en espera', max_length=50),
        ),
    ]
